name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:

      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3

        with:
          github_user_name: FajarAdhitia

          outputs: |
            dist/snake-light.svg?color_snake=%23948979&color_dots=%23E5E1DA,%23DFD0B8,%23C8BFAF,%23AFA493,%23948979
            dist/snake-dark.svg?color_snake=%23DFD0B8&color_dots=%23222831,%23393E46,%23535A62,%23746F65,%23948979

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push snake SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0

        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animation [skip ci]"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
