name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3

        with:
          github_user_name: FajarAdhitia

          outputs: |
            dist/snake-light.svg?color_snake=%232E2A24&color_dots=%23FAF6E9,%23F2EEE2,%23D7D0C0,%236B655A,%232E2A24
            dist/snake-dark.svg?color_snake=%23F5F1E6&color_dots=%23161616,%23242424,%23A89778,%23E6D7B8,%23F5F1E6

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push snake SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0

        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animation [skip ci]"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
